version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - ./api:/usr/src/app/api
      - ./package.json:/usr/src/app/package.json