version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - ./server:/usr/src/app/server
      - ./package.json:/usr/src/app/package.json